[pack-info]
# Pack name
name = ""

# Pack description
description = ""

# Pack version
version = ""

# Pack ID (UUID)
id = ""

# Pack author
author = ""

# Pack cover
cover = "./media/cover.png"

# Pack text hint, this hint will be displayed on bottom of every pack question.
text-hint = ""

# Pack price (must be > 0 if free = false)
price = 0

# Pack preview questions
preview-questions = 3

# Pack number of questions
number-of-questions = 10

# Pack category
category = ""

# Pack is free (if false, price must be > 0)
free = true

# Pack questions
[question1]
question = ""
# Pack question can have one or more answers
answers = [""]

[question2]
question = ""
answers = [""]

[question3]
question = ""
answers = [""]

[question4]
question = ""
answers = [""]

[question5]
question = ""
answers = [""]

[question6]
question = ""
answers = [""]

[question7]
question = ""
answers = [""]

[question8]
question = ""
answers = [""]

[question9]
question = ""
answers = [""]

[question10]
question = ""
answers = [""]
